from selenium import webdriver
from time import sleep
from selenium.webdriver.common.by import By


options=webdriver.ChromeOptions()
options.add_experimental_option("detach",True)
options.add_argument("--disable-notifications")
driver=webdriver.Chrome(options=options)
driver.maximize_window()
driver.get("https://demoapps.qspiders.com/")
sleep(2)
driver.find_element(By.XPATH,"(//main[@data-aos='zoom-in'])[2]").click()
sleep(2)
driver.find_element(By.XPATH,"//section[text()='Frames']").click()
sleep(1)
driver.find_element(By.XPATH,"//section[text()='iframes']").click()
sleep(1)
driver.switch_to.frame(0)
driver.find_element(By.ID,"username").send_keys("abcdef")
driver.find_element(By.ID,"password").send_keys("abc@123")
driver.find_element(By.ID,"submitButton").click()
driver.switch_to.parent_frame()
sleep(2)
driver.find_element(By.LINK_TEXT,"Nested iframe").click()
sleep(2)
driver.switch_to.frame(0)
sleep(2)
driver.switch_to.frame(0)
sleep(2)
driver.find_element(By.ID,"email").send_keys("Krishna@gmail.com")
driver.find_element(By.ID,"password").send_keys("abc@123")
driver.find_element(By.ID,"confirm-password").send_keys("abc@123")
driver.find_element(By.ID,"submitButton").click()
# driver.close()